### ISSUE TITLE
Danish Letter 19310807

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#19] opened 2019-02-15 01:15 UTC
# Source Materials:  
[19310807 Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/19310807)   
[MIWschema.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/WIKIandREADMEmaterials/MIWschema.rng)

**Comment by kschoen3** [comment] 2019-02-19 04:31
Two validation issues show up on this document when checking the text. The first is that the text contains special characters that require editing. The second issue is that attribute name "data-
transient" associated with an element type "meta" must be followed by the ' = ' character.

**Comment by RJP43** [comment] 2019-02-19 04:41
@kschoen3 Whoops, I think something has gone wonky with your schema association. We can work out tomorrow in class what went wrong or @amccann2 might try associating the schema and seeing what she can find. When I associate the project schema to your XML this is what I see:   
![Danish Letter 19310807 validation errors](https://user-images.githubusercontent.com/8645521/52990454-dcf70800-33cd-11e9-8dc9-575765d71764.png)
Notice in the screenshot above that there appears to be only one validation error in your XML when the schema is correctly associated. I applaud you for your attempt 👏 and encourage you to tag me using my handle (@RJP43) in this issue if you have questions.

**Comment by amccann2** [comment] 2019-02-19 19:27
Distinct People & Places 
< title>Letter to <persName key="garlandM">Maria Garland</persName>
< persName key="lili">Lili Ilse Elvenes</persName> 3
< persName key="?">the professor</persName> 2
< persName ref="mb">Maiken Boysen</persName> 1
< persName ref="kj">Kristin Jacobsen</persName> 1
< persName ref="tnm">Tyler Monaghan</persName> 1

some are distinct as first and last name specific and others remain as something less descript. We see this in "garlandM"  versus "the professor."  It should also be noted that most are given an abbreviation of just initials, excluding Lili and Maria Garland -- this probably because these are characters from the text (not certain of this). I am having a hard time understanding where I can find a more extensive list of these/ how to look them up in the XML files. Perhaps I'm downloading the wrong file?

**Comment by amccann2** [comment] 2019-02-19 19:48
TEI Elements 

2 elements featured in these XML elements are the 
< /div> 
< /div> 
AND 
<div type="original"> (and other similar pieces of markup)
 
Translation TEI markup. This is used to distinguish parts of translated letters, or pieces of translated texts to differentiate where they begin and end, because we are trying to organize the languages of multiple different editions. 
there are also publication markups for editions with multiple chapters or sections this is what they look like in just plain TEI 
< /titleStmt>
           < editionStmt>
           < edition/>
           < /editionStmt>
         < publicationStmt>
This is what they look like in our file: 
< publicationStmt>
< p>Publication Information</p>
< /publicationStmt>
< sourceDesc>
< p>Information about the source</p>
< / sourceDesc>
This information is essential because it allows us to search through multiple editions and translations for the differences in publications. here is it important to note that this is different than how we manage the different changes in chapters etc. 

I am not 100% certain if these are exactly what you were looking for.

**Comment by kschoen3** [comment] 2019-02-19 21:18
> Distinct People & Places
> < title>Letter to Maria Garland
> < persName key="lili">Lili Ilse Elvenes 3
> < persName key="?">the professor 2
> < persName ref="mb">Maiken Boysen 1
> < persName ref="kj">Kristin Jacobsen 1
> < persName ref="tnm">Tyler Monaghan 1
> 
> some are distinct as first and last name specific and others remain as something less descript. We see this in "garlandM" versus "the professor." It should also be noted that most are given an abbreviation of just initials, excluding Lili and Maria Garland. I am having a hard time understanding where I can find a more extensive list of these/ how to look them up in the XML files. Perhaps I'm downloading the wrong file?

we found no place names

**Comment by kschoen3** [comment] 2019-02-19 21:30
`<p style="valediction">`
This is a paragraph attribute. It indicates the closing of a letter.

`<p style="salutation">`

Similar to the first one, this element indicates part of a letter. It indicates the greeting or opening of the letter. Both elements divide the text and specify information within the the paragraph.

**Comment by amccann2** [comment] 2019-02-19 21:37
When we went to associate the schema, @kschoen3 and myself (@amccann2) both received an error. We retried to schema association process with @RJP43 and she said she was not sure what this issue was. I am attaching a screenshot file that shows our schema line as well as the error that we encountered


<img width="1431" alt="schemaissue_schoen mccann" src="https://user-images.githubusercontent.com/47229906/53049325-71a84700-345c-11e9-9876-25624247d81f.png">


<img width="861" alt="screen shot 2019-02-19 at 3 39 28 pm" src="https://user-images.githubusercontent.com/47229906/53049382-92709c80-345c-11e9-9ac3-f2baad15996b.png">

**Comment by RJP43** [comment] 2019-02-23 18:53
@kschoen3  and @amccann2 well done completing the TEI XML Exercise! :tada:  I will be asking my fellow technical editor, on the project, if he can identify what went wrong with both of your schema associations and will report back on your issue here with info. as it comes in.    
  
For the next assignment, your team will need to reference the latest file added to the [Danish Letter 19310807 Archival Materials Folder 📂](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/19310807) -- a screenshot of the TEI header information provided by the project manager, Emily Datskou. As a team, you will work together to create a `<teiHeader>` element for Danish Letter 19310807 using the information provided by Emily, the existing XML encoding, photograph(s) of the letter _(a.k.a the facsimile images)_, and the translation/transcription documents.    
 _(⬆️ all available in your text's folder linked above ⬆️)_
  
Be sure to reference the [TEI Header Exercise](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/Exercises/TEIheader_exercise.md) in order to let each other, @ProfPLC, and I know what tasks you each are comfortable with completing by Tuesday (2/26) 📆. Please remember the main goals in all of our assignments are team communication 💬  and collaboration 👐.   
  
 _Note: the TEI header template is available in [Thursday's lesson on Capturing Metadata](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Capturing-Metadata) and as a [download-able XML file containing the template `<teiHeader>`](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/TEIHeader_Template.xml)._ Happy coding! 💻 😃

**Comment by kschoen3** [comment] 2019-02-26 04:00
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   
   <teiHeader>
      <fileDesc>
         <titleStmt>
            
            <title>
               Letter to <persName key="garlandM"></persName>
            </title>            
                        
               <title></title>
               <title xml:lang="eng"></title> 
            
            <Lili Ilse Elvenes>
               <persName key="lili"></persName>
            </author>           
            <respStmt>
               <resp>Photographed <date>August 16-17, 2017</date> by</resp>
               <persName ref="plc">Pamela Caughie</persName>
            </respStmt>
            <respStmt>
               <resp>Images prepared from <date>August to December, 2018</date> by</resp>
               <persName ref="mg">Matthew Gallagher</persName>
            </respStmt>
            <respStmt>
               <resp>Transcription completed from <20> to ,
                     </20> by</resp>
               <persName></persName>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>Translation completed from <20> to ,
                     </30> by</resp>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>Translation reviewed in  <date> to ,
                     </date> by</resp>
               <persName></persName>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>Encoding completed from <date> to ,
                     </date> by</resp>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>Encoding assistance and/or XML proofing completed by</resp>
               <persName ref="rjp">Rebecca J. Parker</persName>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>Assigned <date>Spring 2019</date> Engaged Learner(s)</resp>
               <persName></persName>
               <persName></persName>
            </respStmt>
            <respStmt>
               <resp>XML transformed into HTML on
                     <date></date> by</resp>
               <persName ref="rjp">Rebecca J. Parker</persName>
            </respStmt>
            <respStmt>
               <resp>HTML proofing completed from <date> to ,
                     </date> by</resp>
               <persName></persName>
               <persName></persName>
            </respStmt>
            <sponsor>Loyola University Chicago</sponsor>
            <sponsor>Loyola's Center for Textual Studies and Digital Humanities</sponsor>
            <sponsor>Danish Arts Foundation</sponsor>
         </titleStmt>
         <publicationStmt>
            <authority>Lili Elbe Digital Archive</authority>
            <pubPlace>Chicago, IL, USA</pubPlace>
            <date>July 6th, 2019</date>
            <availability>
               <p>Reproduced by courtesy of the <orgName></orgName> in
                     <placeName></placeName>
               </p>
               <licence>Distributed under a Creative Commons Attribution-NonCommercial-ShareAlike
                  4.0 International licence.</licence>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <p></p>
         </sourceDesc>
      </fileDesc>
   </teiHeader>
   <text>
      <body>
         <p>Some text here.</p>
      </body>
   </text>
</TEI>

**Comment by kschoen3** [comment] 2019-02-26 04:02
> here

hey Audrey, I filled in the necessary information to our header (probably with quite a few mistakes). let me know if you need any help with the next step because i'm not sure if i did all of this correctly.

**Comment by amccann2** [comment] 2019-02-26 17:39
@RJP43 @kschoen3 I have uploaded the document to our folder. I know that there are several issues within the XML document. I wasn't fully sure how to tackle this so I was hoping that we could sit down in class and discuss how to fix these bugs. -audrey

**Comment by amccann2** [comment] 2019-02-26 17:45
one of the TEI header < ClassCode > 
This is a classification of standards that would help us differentiate further between editions, letters, and languages. These classifications would be within the header and at the beginning of any specific text so that we can automatically search for the language, the format, and the edition/time of publication.

**Comment by kschoen3** [comment] 2019-02-26 17:48
I think that using `<note>` would be helpful in order to classify certain marks that the author of the letter includes in the text instead of including them just in the comment of description. Classifying the underlining, circling, emphasis on words, etc. in a systematic way would allow us to communicate more information about the documents.

**Comment by kschoen3** [comment] 2019-02-26 17:50
> one of the TEI header < ClassCode >
> This is a classification of standards that would help us differentiate further between editions, letters, and languages. These classifications would be within the header and at the beginning of any specific text so that we can automatically search for the language, the format, and the edition/time of publication.

I think this is a good point of clarification. It would be interesting to find a way to further organize the letters that we have in the archive.

**Comment by kschoen3** [comment] 2019-02-26 17:52
> @RJP43 @kschoen3 I have uploaded the document to our folder. I know that there are several issues within the XML document. I wasn't fully sure how to tackle this so I was hoping that we could sit down in class and discuss how to fix these bugs. -audrey

I looked over the XML file again as well and couldn't quite figure out where the issues were so I'm on the same page. 👍

**Comment by amccann2** [comment] 2019-02-26 18:01
> I think that using `<note>` would be helpful in order to classify certain marks that the author of the letter includes in the text instead of including them just in the comment of description. Classifying the underlining, circling, emphasis on words, etc. in a systematic way would allow us to communicate more information about the documents.

@kschoen3 !! this is a great idea. It could be super helpful to clarify this, and would allow us to maintain the integrity of the original author's intent. There is a lot to be lost if we don't highlight the importance of small annotations.

**Closed as completed** 2019-03-02 17:19 UTC
Labels: enhancement
