### ISSUE TITLE
Danish Letter 19310131

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#16] opened 2019-02-15 01:11 UTC
# Source Materials:  
[19310131 Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/19310131)   
[MIWschema.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/WIKIandREADMEmaterials/MIWschema.rng)

**Comment by amandallopez** [comment] 2019-02-19 01:14
Hey @Dadelinee! I have just began analyzing the schema, but I was just wondering how you wanted to split up the work, and/or if there was anything you were uncertain about/struggling with. Thanks, let me know!

**Comment by Dadelinee** [comment] 2019-02-19 03:02
Hey @amandallopez sorry! I was in rehearsal just as you sent this. I downloaded the .xml file and the schema. Are we supposed to locate the error in the schema and then upload the file right back here stating the error?

**Comment by RJP43** [comment] 2019-02-19 03:15
@Dadelinee @amandallopez huzzah :tada: well done downloading both files. Once you get the schema associated you will need to reupload the XML to where you downloaded it from. Additionally, you will need to write up a short report on any errors you see in the XML file once the schema is associated. You do not need to correct the errors just report on them here.

**Comment by Dadelinee** [comment] 2019-02-19 03:20
@RJP43 I'm looking in oxygen and for errors in the schema it lists a whole bunch. How do I know which ones to focus on? There's definitely over 100 or so. I can't tell if I associated the schema right either so I'm not sure if it's a problem on my side. Every time I go to assign the schema again through the folder just to make sure, the file is not placed in the desktop folder in oxygen yet when I open all the documents on my computer I can see the txt file sitting in my desktop folder. On oxygen, I only managed to assign it because I searched for it and it found it. However, one of the first errors oxygen tells me is that it couldn't find the schema file so I'm not sure what I'm doing wrong

**Comment by RJP43** [comment] 2019-02-19 03:42
@Dadelinee I am not exactly sure what is happening when you associate the schema that you are seeing so many errors. We will be going over in class how to associate the schema correctly. When I run a validation check on your XML by associating the schema this is what I see: 
![Danish letter 19310131 validation errors](https://user-images.githubusercontent.com/8645521/52988644-ad440200-33c5-11e9-83a1-d6b712410171.png)  
You will notice, once you can get your schema assoicated correctly, that while you have multiple errors they are all for the same reason. I imagine from this screenshot you can tell the reason the errors are occuring, but if not maybe @amandallopez can take a stab at associating the schema and/or identifying the reason for the errors. Hope this helps. Thanks for communicating on your issues board! 😸

**Comment by Dadelinee** [comment] 2019-02-19 04:29
@RJP43 I have both the schema and the .xml document save in the same folder on my computer but I can't seem to get the schema working still

**Comment by Dadelinee** [comment] 2019-02-19 05:26
` <placeName key="lindevangen">Lindevangen</placeName>`key=lindevangen, mentioned 1 times
`<persName key="magnusE">Erwin Magnus</persName>` key=magnusE, mentioned 5 times
`<persName key="?">Hasselbalch</persName>`, no ID, mentioned 8 times
 `<persName key="louLou">` key="louLou", mentioned 2 times
`<persName key="sparreAn">Bé</persName>`Mentioned 4 times, key=sparreAn
`<persName key="kreutz">Werner von Kreutz</persName>` key="kreutz", mentioned 2 times
`<persName key="vibeke">Vibeke</persName>` key=vibeke, mentioned 2 times
Letter to `<persName key="knudsenP">Poul Knudsen</persName>` key=knudsenP, mentioned 5 times
`<placeName key="berlin">Berlin</placeName>` key=berlin, mentioned 2 times
Author `<persName key="lili">Lili Ilse Elvenes</persName>` key="lili", mentioned 3 times
Translation by `<persName ref="kj">Kristin Jacobsen</persName>`
		       `<persName ref="mb">Maiken Boysen</persName>`
Coding by `<persName ref="tnm">Tyler Monaghan</persName>`

**Comment by amandallopez** [comment] 2019-02-19 21:41
@Dadelinee After associating the schema there is one error. The value of attribute "key" is missing for Hr. Hasselbalch. `<persName key="?">Hr. Hasselbalch</persName>` The schema associated version of the XML document has been uploaded.

**Comment by Dadelinee** [comment] 2019-02-20 19:32
The `</p>` element is used to differentiate when a paragraph within the letter would start or end. This helps to keep track of the amount different paragraphs and where they would lie in the letter
Another element is `<div>` Some have attribute values such as "body" in order to show what type of divider it is and helps to show the structure of the letter.

**Comment by amandallopez** [comment] 2019-02-21 17:34
The `<sourceDesc>` element is utilized to signal the description of the source. This provides information about the source that is being encoded. The `<fileDesc>` element is utilized to signify the description of the file. Under the file description, it has been stated that a key is still needed for Hasselbalch. This is useful because it will inform the encoder of the gap that still must be filled.

**Comment by RJP43** [comment] 2019-02-23 18:42
@amandallopez  and @Dadelinee well done communicating so productively on your issue! 💛 Also, well done completing the TEI XML Exercise! :tada:   
  
For the next assignment, your team will need to reference the latest file added to the [Danish Letter 19310131 Archival Materials Folder 📂](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/19310131) -- a screenshot of the TEI header information provided by the project manager, Emily Datskou. As a team, you will work together to create a `<teiHeader>` element for Danish Letter 19310131 using the information provided by Emily, the existing XML encoding, photograph(s) of the letter _(a.k.a the facsimile images)_, and the translation/transcription documents.    
 _(⬆️ all available in your text's folder linked above ⬆️)_
  
Be sure to reference the [TEI Header Exercise](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/Exercises/TEIheader_exercise.md) in order to let each other, @ProfPLC, and I know what tasks you each are comfortable with completing by Tuesday (2/26) 📆. Please remember the main goals in all of our assignments are team communication 💬  and collaboration 👐.   
  
 _Note: the TEI header template is available in [Thursday's lesson on Capturing Metadata](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Capturing-Metadata) and as a [download-able XML file containing the template `<teiHeader>`](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/TEIHeader_Template.xml)._ Happy coding! 💻 😃

**Comment by Dadelinee** [comment] 2019-02-26 18:01
`<title>Letter to <persName key="knudsenP">Poul Knudsen</persName></title>`
`<author><persName key="lili">Lili Ilse Elvenes</persName></author>`
`<respStmt><resp>Photographed <date>August 16-17, 2017</date> by</resp>
<persName ref="plc">Pamela Caughie</persName></respStmt>`
`<respStmt><resp>Images prepared in <date>November 2017</date> by</resp><persName ref="mg">Matthew Gallagher</persName></respStmt>`
`<respStmt>
<resp>Translation completed on <date>November 13, 2017 </date> by</resp>
<persName>ref="kj">Kristin Jacobsen</persName>
<persName ref="mb">Maiken Boysen</persName></respStmt>`
`<respStmt>
               <resp>Translation reviewed from <date><July-September, 2018</date> and <date>November, 2018</date> by</resp>
<persName></persName>
            </respStmt>`
`<respStmt>
<resp>Encoding updated on <date when="2018-11-26">November 26, 2018</date>
</resp><persName ref="tnm">Tyler Monaghan</persName></respStmt>`
` <respStmt>
<resp>Encoding assistance and/or XML proofing completed by</resp>
<persName ref="rjp">Rebecca J. Parker</persName>
<persName> ref="?" Nikolaus Wasmoen</persName> `
`<respStmt>
               <resp>Assigned <date>Spring 2019</date> Engaged Learner(s)</resp>
               <persName>Adeline Azungue</persName>
               <persName>Amanda Lopez</persName>
            </respStmt>`
`</respStmt>
            <sponsor>Loyola University Chicago</sponsor>
            <sponsor>Loyola's Center for Textual Studies and Digital Humanities</sponsor>
            <sponsor>Danish Arts Foundation</sponsor>
         </titleStmt>
         <publicationStmt>
            <authority>Lili Elbe Digital Archive</authority>
            <pubPlace>Chicago, IL, USA</pubPlace>
            <date>July 6th, 2019</date>`
`<availability>
               <p>Reproduced by courtesy of the <orgName></orgName> in
                     <placeName></placeName>
               </p>
               <licence>Distributed under a Creative Commons Attribution-NonCommercial-ShareAlike
                  4.0 International licence.</licence>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <p></p>
         </sourceDesc>
      </fileDesc>`
Hey @amandallopez ! I did about the first half and then some of the info I could find. I added the rest of the TEI template so you could see what I'm referring to (except the HTML portion because I don't think we can fill that in yet right, @RJP43 ?). If you wouldn't mind just filling the last portions of the header. (Also double check I spelled your name correctly lol). I had a hard time finding some of the info like the organization name. And then if you wouldn't mind also doing the source description? Basically just write in anything you think is notable from the picture of the letter we have in our folder. Thanks!

**Comment by Dadelinee** [comment] 2019-02-26 18:18
I think `<projectDesc>` would be good to use in the header because it describes in detail the aim or purpose for which an electronic file was encoded, together with any other relevant information concerning the process by which it was assembled or collected. That way the reason for gathering all of this data and doing all this work can be easily understood by those reading it and emphasizes the importance of our goal.

**Comment by Dadelinee** [comment] 2019-02-26 22:00
@amandallopez heya! Throw down your email address here and I'll send the .xml file your way :^)

**Comment by amandallopez** [comment] 2019-02-26 22:12
@Dadelinee Sounds good, thank you (ღˇᴗˇ) My email is alopez21@luc.edu

**Comment by RJP43** [comment] 2019-02-27 18:42
@amandallopez I suggest uploading the `.xml` file directly to GitHub in your team's folder. Loyola email service will not allow XML file attachments to be read or downloaded. As a reminder instructions to upload directly to GitHub are on our Working in GitHub wiki page, but I have copied them below as well:  

# Adding an existing file directly on GitHub  
1. On GitHub, navigate to the main page of the repository.
2. In your repository, browse to the folder where you want to create a file -- **your team's file folder**  
3. Above the file list, click "Upload files".  
4. Drag and drop the file you'd like to upload to your repository onto the file tree or use the option to browse your computer's file system.  
5. At the bottom of the page, type a short, meaningful commit message indicating what you are uploading.  
6. Below the commit message fields, the default is to add your commit to the current branch. If you're not on the current branch (master), you should select the master branch. Please note you will have had to complete the steps of emailing me, at rparker3 (at) luc (dot) edu, verifying your email and then accepting a collaborator invitation to upload directly in the master branch. If you have not completed these steps you will be brought through a process called a pull request (see examples here) and your file will not be available until someone else in the class who has accepted their collaborator role merges your request.
7. Click "Commit changes".

**Comment by RJP43** [comment] 2019-02-27 18:42
@Dadelinee fantastic statement regarding the `<projectDesc>` element! I think we will probably want to develop this element as the project continues to build out our TEI Header Template. Well done. 🎉 @amandallopez I look forward to your response to @Dadelinee.

**Comment by Dadelinee** [comment] 2019-02-28 17:17
@amandallopez I uploaded the .xml file to the folder if you just wanna throw in the last parts that you have!

**Comment by amandallopez** [comment] 2019-02-28 17:26
@Dadelinee Awesome, thank you! I’m working on it now

**Comment by RJP43** [comment] 2019-02-28 18:16
@amandallopez once you add those finishing touches and upload you will need to respond to @Dadelinee statement regarding the `<projectDesc>` element and post a statement about a different element not used in our header template for @Dadelinee to respond to. See you both in class!

**Comment by amandallopez** [comment] 2019-02-28 18:51
A revision history, tagged `revisionDesc`, would be useful for allowing the encoder to provide a description of the changes being made to the file. This would resolve any questions regarding the development of the electronic text and provides a clear history.

**Comment by amandallopez** [comment] 2019-02-28 18:55
@Dadelinee I agree that `projectDesc` would be an insightful element to utilize because it clearly provides the aim of the document. It also serves as general outline for the project as a whole and might clear up any confusion a reader may have about the content.

**Comment by Dadelinee** [comment] 2019-02-28 19:00
> A revision history, tagged `revisionDesc`, would be useful for allowing the encoder to provide a description of the changes being made to the file. This would resolve any questions regarding the development of the electronic text and provides a clear history.

@amandallopez I agree that this would help a document. That way if someone reading it was confused, they can possibly see who made the change as well as why in order to clear up why maybe another term was used or even why a term was taken out and then replaced with something else. Especially in a project like this, where using the term "transgender" seems logical to us today, it's not something Lili would have known, therefor explaining why that revision was made to a reader could help to clear up the confusion.

**Comment by RJP43** [comment] 2019-02-28 19:01
@amandalopez fantastic responses. I noticed in your recently uploaded XML you inputted your information within the XML comments. You or @dadelinee will want to remove the comment tags around the text you added. Great work.

**Comment by Dadelinee** [comment] 2019-02-28 19:05
> @AmandaLopez fantastic responses. I noticed in your recently uploaded XML you inputted your information within the XML comments. You or @Dadelinee will want to remove the comment tags around the text you added. Great work.

@amandallopez would you mind? I'm in class right now otherwise I would :'^)

**Comment by amandallopez** [comment] 2019-02-28 19:53
@Dadelinee I just re-uploaded it and removed the comment tags!

**Comment by Dadelinee** [comment] 2019-02-28 19:55
@amandallopez you're the best, thank you!

**Closed as completed** 2019-03-02 17:14 UTC
Labels: enhancement
